version: "3.8"

services:

  configserver:
    image: eazybytes/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
     - eazybank

  accounts:
    image: sophiagavrila/accounts
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - bank
    # Docker Compose will ensure that config is started first 
    depends_on:
      - configserver
    # Deploy configurations delays accounts before it makes requests to configserver 
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    # Here we are overriding application.properties of the service    
    environment:
       SPRING_PROFILES_ACTIVE: default
       # Make sure we connect to configserver even if it is not on localhost
       SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
       # Docker is smart enough to determine the IP of where configserver is running
    
  loans:
    image: sophiagavrila/loans
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - bank
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
       SPRING_PROFILES_ACTIVE: default
       SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
    
  cards:
    image: sophiagavrila/cards
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - bank
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
       SPRING_PROFILES_ACTIVE: default
       SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/  
      
networks:
  bank: